package ua.ihromant.hotaabuse;

public enum Unit {
    GREMLIN, GARGOLYE, SKELETON, WALKING_DEAD, WIGHT, VAMPIRE,
    GRAND_ELF, CENTAUR, ZOMBIE,
    THUNDERBIRD, ORC, WOLF_RAIDER, WOLF_RIDER, HOBGOBLIN,
    STEEL_GOLEM,
    UNKNOWN;
}
